[target.'cfg(target_os = "none")']
runner = "probe-run --chip S32K148"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--no-warn-mismatch"
] 
